<script lang="ts">
  import type { EffectInfo, Value } from '../lib/api'
  import { app, Draft } from '../lib/app.svelte'
  import { latest } from '../lib/latest'
  import Icon from './Icon.svelte'
  import ParamField from './ParamField.svelte'
  import Slider from './Slider.svelte'

  type Params = Record<string, Value>

  const CHIP = 'min-h-11 rounded-xl border px-3 text-sm font-medium capitalize transition active:scale-95'
  const CHOSEN = 'border-accent bg-accent/15'
  const IDLE = 'border-line'

  const active = $derived(app.state?.effect?.name ?? null)
  const info = $derived(app.effects.find((effect) => effect.name === active) ?? null)
  const values = new Draft<Params>(() => ({ ...info?.params, ...app.state?.effect?.params }))
  const native = $derived(app.state?.native?.name ?? null)
  const speed = new Draft(() => app.state?.native?.speed ?? 8)
  const [fastest, slowest] = $derived(app.native.speed)

  const settings = new Map<string, Params>() // what each effect was last set to, for coming back to it
  const pushEffect = latest((request: { name: string; params: Params }) => app.send({ cmd: 'effect', ...request }))
  const pushNative = latest((request: { name: string; speed: number }) => app.send({ cmd: 'native', ...request }))

  function start(effect: EffectInfo) {
    if (effect.name !== active) void app.send({ cmd: 'effect', name: effect.name, params: settings.get(effect.name) })
  }

  function change(key: string, value: Value) {
    if (!info) return
    const next = { ...values.value, [key]: value }
    values.set(next)
    settings.set(info.name, next)
    pushEffect({ name: info.name, params: next })
  }

  function changeSpeed(level: number) {
    speed.set(level)
    if (native) pushNative({ name: native, speed: level })
  }
</script>

<div class="grid gap-5">
  <div class="flex min-h-11 items-center justify-between gap-3">
    <div>
      <h2 class="font-semibold">Effects</h2>
      <p class="text-muted text-sm">Generated by the service and streamed to the bulb.</p>
    </div>
    {#if active || native}
      <button
        type="button"
        class="border-line flex h-11 shrink-0 items-center gap-2 rounded-xl border px-3 text-sm font-medium"
        onclick={() => app.send({ cmd: 'stop' })}
      >
        <Icon name="stop" class="size-4" />
        Stop
      </button>
    {/if}
  </div>

  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-2 xl:grid-cols-3">
    {#each app.effects as effect (effect.name)}
      <button
        type="button"
        class={[
          'grid content-start gap-1 rounded-xl border p-3 text-left transition active:scale-[0.98]',
          effect.name === active ? CHOSEN : IDLE,
        ]}
        aria-pressed={effect.name === active}
        onclick={() => start(effect)}
      >
        <span class="flex flex-wrap items-center justify-between gap-x-2 gap-y-1">
          <span class="font-medium capitalize">{effect.name}</span>
          {#if effect.needs}
            <span class="bg-raised text-muted -mr-1 rounded-full px-2 py-0.5 text-xs">{effect.needs}</span>
          {/if}
        </span>
        <span class="text-muted text-sm leading-snug">{effect.summary}</span>
      </button>
    {/each}
  </div>

  {#if info}
    <div class="border-line grid gap-3 rounded-xl border p-4">
      <div class="flex items-baseline justify-between gap-3">
        <h3 class="font-medium"><span class="capitalize">{info.name}</span> settings</h3>
        {#if info.needs}
          <p class="text-muted text-sm">
            {info.needs} from {app.state?.[info.needs] === 'agent' ? 'an agent' : 'this machine'}
          </p>
        {/if}
      </div>
      {#each Object.entries(info.schema) as [key, schema] (key)}
        <ParamField
          name={key}
          {schema}
          value={values.value[key] ?? info.params[key] ?? null}
          onchange={(value) => change(key, value)}
        />
      {/each}
    </div>
  {/if}

  <div class="grid gap-3">
    <div>
      <h2 class="font-semibold">Built into the bulb</h2>
      <p class="text-muted text-sm">Run by the bulb itself; no service needed to keep them going.</p>
    </div>
    <div class="flex flex-wrap gap-2">
      {#each app.native.names as name (name)}
        <button
          type="button"
          class={[CHIP, name === native ? CHOSEN : IDLE]}
          aria-pressed={name === native}
          onclick={() => app.send({ cmd: 'native', name, speed: speed.value })}
        >
          {name.replaceAll('_', ' ')}
        </button>
      {/each}
    </div>
    {#if native}
      <!-- the bulb counts 0 as fastest; the slider runs the other way so right means faster -->
      <Slider
        label="Speed"
        value={slowest - speed.value}
        min={fastest}
        max={slowest}
        shown="{slowest - speed.value + 1} of {slowest - fastest + 1}"
        oninput={(level) => changeSpeed(slowest - level)}
      />
    {/if}
  </div>
</div>
